### ISSUE TITLE
traditional/classic bluetooth support?

### ISSUE THREAD

**Issue by cangSDARM** [GDWired/GDSimpleBLE#3]
Is it possible to use traditional bluetooth through the API provided by the system?

- win32: https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src/Bluetooth/bluetooth-programming-with-windows-sockets.md
- linux: https://www.linux.com/news/understanding-bluetooth-technology-for-linux/
https://www.bluez.org/
- android: https://developer.android.com/guide/topics/connectivity/bluetooth
- macos: https://developer.apple.com/documentation/corebluetooth

or maybe corss-platform:
https://github.com/chromium/chromium/tree/main/device/bluetooth
https://github.com/tinygo-org/bluetooth

**Comment by jferdelyi** [comment]
Hi, sorry for the delay : I'm using SimpleBLE that is BLE only (https://github.com/OpenBluetoothToolbox/SimpleBLE)

**Comment by cangSDARM** [comment]
Yes, I know `simpleble` only supports ble. I mean is it possible to extend to support classic bluetooth using the apis I mentioned?

**Comment by jferdelyi** [comment]
Hello,
- This one is only for BLE https://github.com/tinygo-org/bluetooth
- This one seems complicated and is for BLE and Classic BT (https://github.com/chromium/chromium/tree/main/device/bluetooth)
- Developing a cross-platform classic Bluetooth library from scratch doesn't seem like a good idea, I don't have much time to devote to it.

I also found this library (https://github.com/Agamnentzar/bluetooth-serial-port) 

I don't know if I'm going to implement classic Bluetooth in this plugin, but maybe I'll create a new one dedicated to it.

**Comment by cangSDARM** [comment]
Thx!
