### ISSUE TITLE
SimpleBLE new license (GPLv3) note

### ISSUE THREAD

**Issue by SebaLukas** [GDWired/GDSimpleBLE#4]
Hi :)

I think this project is really great and would love to use this plugin. But that is not possible because of the license of SimpleBLE.

Since February 2024 the license of SimpleBLE has changed to GPLv3. This means that for commercial closed-source projects, either you open your project to open-source and GPLv3 or you can no longer use SimpleBLE. (Of course you can also contact the maintainer and ask for a fee to lift the GPLv3 license)

Therefore I would like to ask you: Can you add a note in your repo that the license of SimpleBLE has changed to GPLv3 and what consequences this has for commercial closed source projects if these projects use your plugin.

Thank you very much :)

**Comment by jferdelyi** [comment]
Hello, ho ok I will change it thank you
